# Generated by Django 3.2.25 on 2025-01-19 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attunement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_eng', models.CharField(max_length=100, unique=True)),
                ('short', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CastTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DndClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('style', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('style', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('base_race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subraces', to='tentaculus.race')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('base_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subclasses', to='tentaculus.dndclass')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_eng', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_face_side', models.BooleanField(default=True)),
                ('name_font_size', models.DecimalField(decimal_places=2, default=14, max_digits=4)),
                ('font_size', models.DecimalField(decimal_places=2, default=11.25, max_digits=4)),
                ('description', models.TextField()),
                ('footer_font_size', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('circle', models.IntegerField(choices=[(-1, '---'), (0, 'Заговор'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')])),
                ('is_ritual', models.BooleanField(default=False)),
                ('components', models.TextField(choices=[('В', 'В'), ('С', 'С'), ('М', 'М'), ('В, С', 'В, С'), ('В, М', 'В, М'), ('С, М', 'С, М'), ('В, С, М', 'В, С, М')])),
                ('material_component', models.CharField(blank=True, max_length=100, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tentaculus.book')),
                ('cast_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tentaculus.casttime')),
                ('classes', models.ManyToManyField(blank=True, to='tentaculus.DndClass')),
                ('distance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tentaculus.distance')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tentaculus.duration')),
                ('race', models.ManyToManyField(blank=True, to='tentaculus.Race')),
                ('school', models.ManyToManyField(related_name='spells', to='tentaculus.School')),
                ('second_side', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tentaculus.spell')),
                ('subclasses', models.ManyToManyField(blank=True, to='tentaculus.SubClass')),
                ('subrace', models.ManyToManyField(blank=True, to='tentaculus.SubRace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_eng', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_face_side', models.BooleanField(default=True)),
                ('name_font_size', models.DecimalField(decimal_places=2, default=14, max_digits=4)),
                ('font_size', models.DecimalField(decimal_places=2, default=11.25, max_digits=4)),
                ('description', models.TextField()),
                ('footer_font_size', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rarity', models.TextField(choices=[('Обычный', 'Обычный'), ('Необычный', 'Необычный'), ('Редкий', 'Редкий'), ('Очень редкий', 'Очень редкий'), ('Легендарный', 'Легендарный'), ('Артифакт', 'Артифакт')])),
                ('attunement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tentaculus.attunement')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tentaculus.book')),
                ('item_types', models.ManyToManyField(related_name='items', to='tentaculus.ItemType')),
                ('second_side', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tentaculus.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
