# Generated by Django 4.1.7 on 2025-02-22 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='second_side',
            new_name='second_side_spell',
        ),
        migrations.RenameField(
            model_name='spell',
            old_name='second_side',
            new_name='second_side_spell',
        ),
    ]
