# Generated by Django 4.1.7 on 2024-11-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='components',
            field=models.TextField(choices=[('V', 'В'), ('S', 'С'), ('M', 'М'), ('VS', 'В, С'), ('VM', 'В, М'), ('SM', 'С, М'), ('VSM', 'В, С, М')]),
        ),
    ]
