# Generated by Django 4.1.7 on 2024-11-04 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tentaculus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attunement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_eng', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('name_font_size', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('font_size', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('description', models.TextField()),
                ('footer_font_size', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tentaculus.book')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('second_side', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tentaculus.card')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='CastTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('style', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='spell',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='spell',
            name='book',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='description',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='footer_font_size',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='id',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='name',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='source',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='style',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='title',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='title_font_size',
        ),
        migrations.AlterField(
            model_name='spell',
            name='components',
            field=models.TextField(choices=[('V', 'В'), ('S', 'С'), ('M', 'М'), ('VS', 'В, С'), ('VM', 'В, М'), ('SM', 'С, М'), ('VSM', 'В, С, М')]),
        ),
        migrations.RemoveField(
            model_name='spell',
            name='school',
        ),
        migrations.AddField(
            model_name='spell',
            name='card_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tentaculus.card'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spell',
            name='class_race',
            field=models.ManyToManyField(related_name='spells', to='tentaculus.classrace'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='cast_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tentaculus.casttime'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='distance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tentaculus.distance'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tentaculus.duration'),
        ),
        migrations.AddField(
            model_name='spell',
            name='school',
            field=models.ManyToManyField(related_name='spells', to='tentaculus.school'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tentaculus.card')),
                ('rarity', models.TextField(choices=[('Обычный', 'Обычный'), ('Необычный', 'Необычный'), ('Редкий', 'Редкий'), ('Очень редкий', 'Очень редкий'), ('Легендарный', 'Легендарный'), ('Артифакт', 'Артифакт')])),
                ('attunement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tentaculus.attunement')),
                ('item_types', models.ManyToManyField(related_name='items', to='tentaculus.itemtype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('tentaculus.card',),
        ),
    ]
