# Generated by Django 4.1.7 on 2025-03-14 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0002_rename_second_side_item_second_side_spell_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_types',
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='tentaculus.itemtype'),
        ),
    ]
