# Generated by Django 4.1.7 on 2024-11-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0003_alter_spell_material_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='components',
            field=models.TextField(choices=[('В', 'В'), ('С', 'С'), ('М', 'М'), ('В, С', 'В, С'), ('В, М', 'В, М'), ('С, М', 'С, М'), ('В, С, М', 'В, С, М')]),
        ),
    ]
