# Generated by Django 4.1.7 on 2024-11-03 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0003_casttime_distance_duration_alter_spell_cast_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='spell',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tentaculus.cardstyle'),
        ),
    ]
