# Generated by Django 4.1.7 on 2024-11-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0004_cardstyle_alter_spell_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='school',
            field=models.TextField(choices=[('Abjuration', 'Ограждение'), ('Biomancy', 'Биомантия'), ('Chronomancy', 'Хрономантия'), ('Conjuration', 'Вызов'), ('Divination', 'Прорицание'), ('Graviturgy', 'Гравитургия'), ('Enchantment', 'Очарование'), ('Evocation', 'Воплощение'), ('Hemocraft', 'Гемокрафт'), ('Necromancy', 'Некромантия'), ('Transmutatuion', 'Преобразование')]),
        ),
    ]
