# Generated by Django 4.1.7 on 2025-03-15 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0004_item_second_side_item_spell_second_side_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='requirements',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tentaculus.itemrequirements'),
        ),
    ]
