# Generated by Django 4.1.7 on 2024-11-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0004_source_remove_spell_class_race_card_is_face_side_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='class_race',
            field=models.ManyToManyField(to='tentaculus.source'),
        ),
    ]
