# Generated by Django 4.1.7 on 2024-11-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0004_alter_spell_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_base',
            field=models.BooleanField(default=False),
        ),
    ]
