# Generated by Django 4.1.7 on 2024-11-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0005_spell_class_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='is_ritual',
            field=models.BooleanField(default=False),
        ),
    ]
