# Generated by Django 4.1.7 on 2025-03-15 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0005_itemrequirements_item_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='requirements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tentaculus.itemrequirements'),
        ),
    ]
