# Generated by Django 4.1.7 on 2024-11-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0005_alter_spell_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('style', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='spell',
            name='source',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='style',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='school',
        ),
        migrations.AddField(
            model_name='spell',
            name='class_race',
            field=models.ManyToManyField(related_name='spells', to='tentaculus.classrace'),
        ),
        migrations.AddField(
            model_name='spell',
            name='school',
            field=models.ManyToManyField(related_name='spells', to='tentaculus.school'),
        ),
    ]
