# Generated by Django 4.1.7 on 2024-11-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0005_school_is_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='is_base',
        ),
        migrations.AddField(
            model_name='school',
            name='priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
