# Generated by Django 4.1.7 on 2024-11-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0006_remove_school_is_base_school_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_face_sice',
            field=models.BooleanField(default=True),
        ),
    ]
