# Generated by Django 4.1.7 on 2024-11-03 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0006_classrace_school_remove_spell_source_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardStyle',
        ),
    ]
