# Generated by Django 4.1.7 on 2024-11-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0006_spell_is_ritual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='class_race',
        ),
        migrations.AddField(
            model_name='spell',
            name='classes',
            field=models.ManyToManyField(blank=True, null=True, to='tentaculus.dndclass'),
        ),
        migrations.AddField(
            model_name='spell',
            name='race',
            field=models.ManyToManyField(blank=True, null=True, to='tentaculus.race'),
        ),
        migrations.AddField(
            model_name='spell',
            name='subclasses',
            field=models.ManyToManyField(blank=True, null=True, to='tentaculus.subclass'),
        ),
        migrations.AddField(
            model_name='spell',
            name='subrace',
            field=models.ManyToManyField(blank=True, null=True, to='tentaculus.subrace'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='circle',
            field=models.IntegerField(choices=[(-1, '---'), (0, 'Заговор'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')]),
        ),
    ]
