# Generated by Django 4.1.7 on 2025-03-17 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0006_alter_item_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='is_ability',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spell',
            name='cast_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tentaculus.casttime'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='components',
            field=models.TextField(blank=True, choices=[('В', 'В'), ('С', 'С'), ('М', 'М'), ('В, С', 'В, С'), ('В, М', 'В, М'), ('С, М', 'С, М'), ('В, С, М', 'В, С, М')], null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='distance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tentaculus.distance'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='duration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tentaculus.duration'),
        ),
    ]
