# Generated by Django 4.1.7 on 2025-03-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0007_spell_is_ability_alter_spell_cast_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='circle',
            field=models.IntegerField(blank=True, choices=[(-1, '---'), (0, 'Заговор'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], null=True),
        ),
    ]
