# Generated by Django 4.1.7 on 2024-11-03 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0007_delete_cardstyle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='title',
            new_name='title_eng',
        ),
    ]
