# Generated by Django 4.1.7 on 2024-11-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0007_card_is_face_sice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='is_face_sice',
            new_name='is_face_side',
        ),
    ]
