# Generated by Django 4.1.7 on 2024-11-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0007_remove_spell_class_race_spell_classes_spell_race_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ('name',)},
        ),
    ]
