# Generated by Django 4.1.7 on 2024-11-03 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0008_rename_title_spell_title_eng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='title_font_size',
            new_name='name_font_size',
        ),
    ]
