# Generated by Django 3.2.25 on 2024-12-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0008_alter_source_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title_eng',
            field=models.CharField(default='Homebrew', max_length=100),
            preserve_default=False,
        ),
    ]
