# Generated by Django 4.1.7 on 2024-11-03 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0009_rename_title_font_size_spell_name_font_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_eng', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('name_font_size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('font_size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField()),
                ('footer_font_size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('attunement', models.BooleanField(default=False)),
                ('rarity', models.TextField(choices=[('common', 'Обычный'), ('uncommon', 'Необычный'), ('rare', 'Редкий'), ('very rare', 'Очень редкий'), ('legendary', 'Легендарный'), ('artifact', 'Артифакт')])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tentaculus.book')),
                ('item_type', models.ManyToManyField(related_name='items', to='tentaculus.itemtype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
