# Generated by Django 4.1.7 on 2024-11-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0010_itemtype_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='attunement',
            field=models.CharField(max_length=30),
        ),
    ]
