# Generated by Django 3.2.25 on 2024-12-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0010_alter_casttime_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='font_size',
            field=models.DecimalField(blank=True, decimal_places=2, default=11.25, max_digits=4, null=True),
        ),
    ]
