# Generated by Django 3.2.25 on 2024-12-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0011_alter_card_font_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='font_size',
            field=models.DecimalField(decimal_places=2, default=11.25, max_digits=4),
        ),
    ]
