# Generated by Django 3.2.25 on 2024-12-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0012_alter_card_font_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name_font_size',
            field=models.DecimalField(decimal_places=2, default=14, max_digits=4),
        ),
    ]
