# Generated by Django 4.1.7 on 2024-11-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0012_attunement_alter_item_attunement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='font_size',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='footer_font_size',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name_font_size',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='font_size',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='footer_font_size',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='name_font_size',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
