# Generated by Django 3.2.25 on 2024-12-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0013_alter_card_name_font_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
