# Generated by Django 3.2.25 on 2025-01-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0014_alter_source_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attunement',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='short',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title_eng',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='casttime',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='distance',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='dndclass',
            name='style',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='duration',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='style',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='classes',
            field=models.ManyToManyField(blank=True, to='tentaculus.DndClass'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='race',
            field=models.ManyToManyField(blank=True, to='tentaculus.Race'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='subclasses',
            field=models.ManyToManyField(blank=True, to='tentaculus.SubClass'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='subrace',
            field=models.ManyToManyField(blank=True, to='tentaculus.SubRace'),
        ),
    ]
