# Generated by Django 4.1.7 on 2024-11-04 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0014_alter_item_font_size_alter_item_footer_font_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='second_side',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tentaculus.item'),
        ),
        migrations.AddField(
            model_name='spell',
            name='second_side',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tentaculus.spell'),
        ),
    ]
