# Generated by Django 4.1.7 on 2024-11-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0015_item_second_side_spell_second_side'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_type',
            new_name='item_types',
        ),
    ]
