# Generated by Django 4.1.7 on 2024-11-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0016_rename_item_type_item_item_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.TextField(choices=[('Обычный', 'Common'), ('Необычный', 'Uncommon'), ('Редкий', 'Rare'), ('Очень редкий', 'Very Rare'), ('Легендарный', 'Legendary'), ('Артифакт', 'Artifact')]),
        ),
    ]
