# Generated by Django 4.1.7 on 2024-11-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tentaculus', '0017_alter_item_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.TextField(choices=[('Обычный', 'Обычный'), ('Необычный', 'Необычный'), ('Редкий', 'Редкий'), ('Очень редкий', 'Очень редкий'), ('Легендарный', 'Легендарный'), ('Артифакт', 'Артифакт')]),
        ),
    ]
